package services

import (
	"fmt"

	"github.com/google/uuid"
	"github.com/rpupo63/faradhaven/backend/database"
	"github.com/rpupo63/faradhaven/backend/models"
)

// SpellSynthesis holds auto-derived suggestions from a set of components.
type SpellSynthesis struct {
	Level                    int              `json:"level"`
	SuggestedType            models.SpellType `json:"suggested_type"`
	SuggestedRange           *int             `json:"suggested_range,omitempty"`
	SuggestedDamageType      *string          `json:"suggested_damage_type,omitempty"`
	SuggestedDamageDiceCount *int             `json:"suggested_damage_dice_count,omitempty"`
	SuggestedDamageDieSize   *int             `json:"suggested_damage_die_size,omitempty"`
	SuggestedDuration        *string          `json:"suggested_duration,omitempty"`
	SuggestedConcentration   bool             `json:"suggested_concentration"`
	ValidationErrors         []string         `json:"validation_errors"`
}

// SpellSynthesisService computes spell properties from components.
type SpellSynthesisService struct {
	componentRepo *database.ComponentRepo
}

type componentPhase struct {
	number     int
	components []models.Component
}

// NewSpellSynthesisService creates a new SpellSynthesisService.
func NewSpellSynthesisService(componentRepo *database.ComponentRepo) *SpellSynthesisService {
	return &SpellSynthesisService{componentRepo: componentRepo}
}

// FetchComponents retrieves components by their IDs in request order (duplicates preserved).
func (s *SpellSynthesisService) FetchComponents(ids []uuid.UUID) ([]models.Component, error) {
	return s.componentRepo.GetComponentsByIDsOrdered(ids)
}

// splitNonLogicaPhases returns non-empty non-Logica runs in chain order.
// This mirrors ComponentFingerprint phase boundaries for validation consistency.
func splitNonLogicaPhases(components []models.Component) []componentPhase {
	phases := make([]componentPhase, 0)
	current := make([]models.Component, 0)
	phaseNum := 1

	flush := func() {
		if len(current) == 0 {
			return
		}
		phaseComponents := append([]models.Component(nil), current...)
		phases = append(phases, componentPhase{number: phaseNum, components: phaseComponents})
		phaseNum++
		current = current[:0]
	}

	for _, c := range components {
		if c.Category == models.CategoryLogica {
			flush()
			continue
		}
		current = append(current, c)
	}
	flush()

	return phases
}

// Validate checks component MECE rules and returns any violations.
func (s *SpellSynthesisService) Validate(components []models.Component) []string {
	var errors []string

	var essentiaCount int
	var hasIncrease, hasDecrease, hasStrong, hasWeak bool

	for _, c := range components {
		switch c.Category {
		case models.CategoryLogica:
			continue
		case models.CategoryForma:
		case models.CategoryScopus:
		case models.CategoryEssentia:
			essentiaCount++
		case models.CategoryMagnitudo:
			switch c.Name {
			case "Increase":
				hasIncrease = true
			case "Decrease":
				hasDecrease = true
			case "Strong":
				hasStrong = true
			case "Weak":
				hasWeak = true
			}
		}
	}

	phases := splitNonLogicaPhases(components)
	for _, phase := range phases {
		phaseFormaCount := 0
		phaseScopusCount := 0
		for _, comp := range phase.components {
			switch comp.Category {
			case models.CategoryForma:
				phaseFormaCount++
			case models.CategoryScopus:
				phaseScopusCount++
			}
		}
		if phaseFormaCount == 0 {
			errors = append(errors, fmt.Sprintf("Phase %d requires exactly 1 Forma (shape) component", phase.number))
		} else if phaseFormaCount > 1 {
			errors = append(errors, fmt.Sprintf("Phase %d allows only 1 Forma (shape) component", phase.number))
		}
		if phaseScopusCount == 0 {
			errors = append(errors, fmt.Sprintf("Phase %d requires exactly 1 Scopus (targeting) component", phase.number))
		} else if phaseScopusCount > 1 {
			errors = append(errors, fmt.Sprintf("Phase %d allows only 1 Scopus (targeting) component", phase.number))
		}
	}

	if essentiaCount == 0 {
		errors = append(errors, "At least 1 Essentia (element/domain) component is required")
	}

	if hasIncrease && hasDecrease {
		errors = append(errors, "Cannot use both Increase and Decrease modifiers")
	}
	if hasStrong && hasWeak {
		errors = append(errors, "Cannot use both Strong and Weak modifiers")
	}

	return errors
}

// Synthesize derives spell property suggestions from a set of components.
func (s *SpellSynthesisService) Synthesize(components []models.Component) *SpellSynthesis {
	return s.SynthesizeWithOverrides(components, nil, nil)
}

// SynthesizeWithOverrides derives spell properties and lets callers provide optional draft overrides.
func (s *SpellSynthesisService) SynthesizeWithOverrides(
	components []models.Component,
	damageTypeOverride *models.DamageType,
	rangeOverride *int,
) *SpellSynthesis {
	syn := &SpellSynthesis{
		SuggestedType: models.SpellTypeUtility,
	}

	syn.ValidationErrors = s.Validate(components)

	// Level is autogenerated by the number of components
	syn.Level = len(components)

	var formaName string
	var scopusName string
	var magnitudes []string
	var hasDamage bool

	// For multi-phase chains, synthesis currently uses the first Forma/Scopus seen in
	// flat order. For later phases with different pairs, whole-spell suggestions remain
	// approximate until phase-aware synthesis is implemented.
	for _, c := range components {
		switch c.Category {
		case models.CategoryLogica:
			continue
		case models.CategoryEssentia:
			if c.Element != "" {
				mapped := mapElementToDamageType(c.Element)
				if parsed, ok := models.ParseDamageType(mapped); ok {
					s := string(parsed)
					syn.SuggestedDamageType = &s
					hasDamage = true
				}
			}

		case models.CategoryForma:
			formaName = c.Name
			r := mapFormaToRangeFeet(c.Name)
			syn.SuggestedRange = &r

			// Concentration for sustained shapes
			switch c.Name {
			case "Zone", "Wall", "Aura":
				syn.SuggestedConcentration = true
				dur := "1 min"
				syn.SuggestedDuration = &dur
			}

		case models.CategoryScopus:
			scopusName = c.Name

		case models.CategoryActio:
			syn.SuggestedType = mapActioToSpellType(c.Name)

			// Concentration for Bind
			if c.Name == "Bind" {
				syn.SuggestedConcentration = true
				dur := "1 min"
				syn.SuggestedDuration = &dur
			}

		case models.CategoryMagnitudo:
			magnitudes = append(magnitudes, c.Name)
		}
	}

	if rangeOverride != nil {
		// Draft range override: keep synthesis response aligned with current forge edits.
		r := *rangeOverride
		syn.SuggestedRange = &r
	}

	if damageTypeOverride != nil {
		s := string(*damageTypeOverride)
		syn.SuggestedDamageType = &s
		hasDamage = true
	}

	// Compute damage dice via Laws of Equivalency
	if hasDamage && syn.SuggestedDamageType != nil {
		dmgType := models.DamageType(*syn.SuggestedDamageType)
		pool := CalculateSpellEffect(syn.Level, dmgType, formaName, scopusName, magnitudes)
		c, f := pool.Count, pool.Faces
		syn.SuggestedDamageDiceCount = &c
		syn.SuggestedDamageDieSize = &f
	}

	return syn
}

// mapElementToDamageType maps component Element strings to D&D damage types.
func mapElementToDamageType(element string) string {
	switch element {
	case "Fire":
		return "Fire"
	case "Cold":
		return "Cold"
	case "Lightning":
		return "Lightning"
	case "Thunder":
		return "Thunder"
	case "Acid":
		return "Acid"
	case "Poison":
		return "Poison"
	case "Necrotic":
		return "Necrotic"
	case "Radiant":
		return "Radiant"
	case "Force":
		return "Force"
	case "Psychic":
		return "Psychic"
	case "Bludgeoning":
		return "Bludgeoning"
	case "Piercing":
		return "Piercing"
	case "Slashing":
		return "Slashing"
	default:
		return element
	}
}

// mapFormaToRangeFeet maps Forma component names to range in feet (0 = self-centered shapes).
func mapFormaToRangeFeet(name string) int {
	switch name {
	case "Touch":
		return 5
	case "Projectile":
		return 120
	case "Lance":
		return 150
	case "Beam":
		return 100
	case "Arc":
		return 90
	case "Nova":
		return 0
	case "Cone":
		return 0
	case "Wall":
		return 120
	case "Pillar":
		return 120
	case "Zone":
		return 90
	case "Ring":
		return 60
	case "Aura":
		return 0
	case "Orbit":
		return 60
	default:
		return 60
	}
}

// mapActioToSpellType maps Actio component names to spell types.
func mapActioToSpellType(name string) models.SpellType {
	switch name {
	case "Push", "Pull", "Crush", "Pierce":
		return models.SpellTypeAttack
	case "Create":
		return models.SpellTypeUtility
	case "Bind", "Grab":
		return models.SpellTypeSave
	case "Mutate":
		return models.SpellTypeEffect
	case "Destroy":
		return models.SpellTypeAttack
	case "Lift", "Spin":
		return models.SpellTypeSave
	default:
		return models.SpellTypeUtility
	}
}
