package faradhaven_storeowners

// AllStoreOwnerSeeds returns all vendor definitions (order stable for hashing).
// Each CatalogRuleSeed row maps to one store_owner_catalog_rules record.
// ItemName / WeaponName values MUST match Name fields in faradhaven_items (AllItems / AllWeapons).
func AllStoreOwnerSeeds() []StoreOwnerSeed {
	return []StoreOwnerSeed{
		// --- Apothecary: district potions + antitoxins ---
		{
			Name:                  "Mireya Vex",
			Location:              "Ash Quarter, Faradhaven — Vex Apothecary (under the Viridian-tinted eaves)",
			Personality:           "Classic sharp-tongued alchemist: curious about odd reagents, overcharges strangers, remembers every face that slighted her.",
			WillingnessToPurchase: 0.85,
			ExchangeRate:          1.15,
			CategoriesObtained:    []string{"Potion", "Gear"},
			Rules: []CatalogRuleSeed{
				{Category: "Potion", AllowedRarities: []string{"Common", "Uncommon"}},
				{ItemName: "Healing Potion"},
				{ItemName: "Greater Healing Potion"},
				{ItemName: "Steam-Breath Elixir"},
				{ItemName: "Smog-Filter Lozenge"},
				{ItemName: "Alchemical Accelerant"},
				{ItemName: "Stabilizer Serum"},
				{ItemName: "Antitoxin (vial)"},
				{ItemName: "Industrial Respirator"},
			},
		},
		// --- Smith: common martial stock + Faradhaven folding blade ---
		{
			Name:                  "Torven Ironwright",
			Location:              "Foundry Row — Ironwright Smithy (coal smoke and honest rivets)",
			Personality:           "Gruff master smith: proud of Faradhaven steel, dismissive of 'aerostat tin' imports.",
			WillingnessToPurchase: 0.9,
			ExchangeRate:          1.1,
			CategoriesObtained:    []string{"Simple Melee", "Martial Melee", "Simple Ranged", "Martial Ranged"},
			Rules: []CatalogRuleSeed{
				{Category: "Simple Melee", AllowedRarities: []string{"Common", "Uncommon"}},
				{Category: "Martial Melee", AllowedRarities: []string{"Common", "Uncommon"}},
				{WeaponName: "Folding Blade"},
				{WeaponName: "Shortsword"},
				{WeaponName: "Longsword"},
				{WeaponName: "Warhammer"},
				{WeaponName: "Handaxe"},
				{WeaponName: "Light Crossbow"},
			},
		},
		// --- Fence: illicit tools, poisons, copper economy ---
		{
			Name:                  "Silas Coppertooth",
			Location:              "Copper Veins crawlspace — no sign, no Faradollars (Homunculi trade night)",
			Personality:           "The shady fence archetype: wet smile, dry purse, weighs your soul like scrap copper. Asks few questions.",
			WillingnessToPurchase: 0.42,
			ExchangeRate:          1.38,
			CategoriesObtained:    []string{"Gear", "Tool", "Potion"},
			Rules: []CatalogRuleSeed{
				{ItemName: "Thieves' Tools"},
				{ItemName: "Basic Poison (vial)"},
				{ItemName: "Poisoner's Kit"},
				{ItemName: "Disguise Kit"},
				{ItemName: "Dark Cloak"},
				{ItemName: "Homunculus Copper Slug (1 lb)"},
				{ItemName: "No-Go Alley Chalk Set"},
				{Category: "Tool", AllowedRarities: []string{"Common"}},
			},
		},
		// --- Luxury salon: rare consumables + fine tools ---
		{
			Name:                  "Lady Morwyn Ashford-Keir",
			Location:              "Aerostat Estates salon — by appointment via ETC lift (perfume masks the ozone)",
			Personality:           "Snobby couture-boutique energy: inspects your gloves before speaking; prices assume you summer above the Static Haze.",
			WillingnessToPurchase: 0.52,
			ExchangeRate:          1.48,
			CategoriesObtained:    []string{"Potion", "Tool", "Gear"},
			Rules: []CatalogRuleSeed{
				{Category: "Potion", AllowedRarities: []string{"Rare", "Very Rare"}},
				{ItemName: "Elixir of Health"},
				{ItemName: "Potion of Invisibility"},
				{ItemName: "Oil of Sharpness"},
				{ItemName: "Jeweler's Tools"},
				{ItemName: "ETC Day-Pass Chit"},
				{ItemName: "Aerostat Silk Gloves"},
			},
		},
		// --- Military quartermaster ---
		{
			Name:                  "Sergeant Karrick Venn",
			Location:              "ACC concession — cordoned lane near the Hum exhibition grounds",
			Personality:           "Quartermaster trope: clipboard, stamp, zero patience for 'civilian flair.' Everything catalogued.",
			WillingnessToPurchase: 0.72,
			ExchangeRate:          1.06,
			CategoriesObtained:    []string{"Martial Melee", "Martial Ranged", "Simple Ranged"},
			Rules: []CatalogRuleSeed{
				{Category: "Martial Melee", AllowedRarities: []string{"Common", "Uncommon"}},
				{Category: "Martial Ranged", AllowedRarities: []string{"Common", "Uncommon"}},
				{WeaponName: "Longsword"},
				{WeaponName: "Spear"},
				{WeaponName: "Heavy Crossbow"},
				{WeaponName: "Light Crossbow"},
				{ItemName: "ACC Armorer's Grease Tin"},
			},
		},
		// --- DCC clinical / specimens ---
		{
			Name:                  "Dr. Thessaly Morrow",
			Location:              "DCC exhibition annex — glass cases, brass rails, whisper of sanitizer and oil",
			Personality:           "Clinical showroom host: treats customers like promising test subjects; genuinely excited by 'novel tissue.'",
			WillingnessToPurchase: 0.78,
			ExchangeRate:          1.2,
			CategoriesObtained:    []string{"Tool", "Potion", "Gear"},
			Rules: []CatalogRuleSeed{
				{Category: "Potion", AllowedRarities: []string{"Uncommon", "Rare"}},
				{ItemName: "Anatomist's Kit"},
				{ItemName: "Specimen Preservation Jar"},
				{ItemName: "Sanguine Extraction Pump"},
				{ItemName: "Healer's Kit"},
			},
		},
		// --- Street general merchant ---
		{
			Name:                  "Jasper Quick",
			Location:              "Street stall, Foundry Row — bell rings when the Viridian Shroud thins",
			Personality:           "Cheerful general merchant: whistles, rounds down for kids, overcharges anyone in a Triple P tabard.",
			WillingnessToPurchase: 1.0,
			ExchangeRate:          1.02,
			CategoriesObtained:    []string{"Gear"},
			Rules: []CatalogRuleSeed{
				{Category: "Gear", AllowedRarities: []string{"Common", "Uncommon"}},
				{ItemName: "Healer's Kit"},
				{ItemName: "Explorer's Pack"},
				{ItemName: "Dungeoneer's Pack"},
				{ItemName: "Rope, Hempen (50 feet)"},
				{ItemName: "Torch"},
				{ItemName: "Rations (1 day)"},
				{ItemName: "Waterskin"},
			},
		},
		// --- Curio shop: optics & precision tools ---
		{
			Name:                  "Orla Mire-thorn",
			Location:              "Curio & Oddity — Static Haze district (lantern always 'just faulty')",
			Personality:           "Eccentric collector shopkeep: every item has a tragedy attached; may trade for stories.",
			WillingnessToPurchase: 0.68,
			ExchangeRate:          1.28,
			CategoriesObtained:    []string{"Gear", "Tool"},
			Rules: []CatalogRuleSeed{
				{Category: "Tool", AllowedRarities: []string{"Common", "Uncommon"}},
				{ItemName: "Magnifying Glass"},
				{ItemName: "Spyglass"},
				{ItemName: "Aetheric Tuning Fork"},
				{ItemName: "Clockwork Chronometer"},
				{ItemName: "Clockwork Lockbox"},
			},
		},
		// --- Pneumatic gunsmith ---
		{
			Name:                  "Willem Gearhart",
			Location:              "Gearhart Pneumatic — between two hissing mains near the industrial stacks",
			Personality:           "Mad-inventor gunsmith: grease under nails, laughs at 'elegant' weapons; lives for pressure gauges.",
			WillingnessToPurchase: 0.82,
			ExchangeRate:          1.22,
			CategoriesObtained:    []string{"Martial Ranged", "Simple Ranged", "Tool"},
			Rules: []CatalogRuleSeed{
				{Category: "Martial Ranged", AllowedRarities: []string{"Uncommon", "Rare"}},
				{WeaponName: "Steam-Pressure Rifle"},
				{WeaponName: "Pneumatic Crossbow"},
				{WeaponName: "Pepperbox Revolver"},
				{ItemName: "Tinker's Tools"},
				{ItemName: "Bag of Gears and Springs"},
				{ItemName: "Mechanized Oil Can"},
				{ItemName: "Stability Pressure Gauge"},
				{ItemName: "Piston Core Assembly Kit"},
			},
		},
		// --- Shrine vendor ---
		{
			Name:                  "Brother Coalwick",
			Location:              "Shrine stall — South Axiom pilgrim lane (incense cuts the smog)",
			Personality:           "Soft-spoken temple vendor trope: blesses your change; quietly notes if you're running from something.",
			WillingnessToPurchase: 0.88,
			ExchangeRate:          1.08,
			CategoriesObtained:    []string{"Gear"},
			Rules: []CatalogRuleSeed{
				{ItemName: "Holy Water (flask)"},
				{ItemName: "Holy Symbol (Amulet)"},
				{ItemName: "Holy Symbol (Reliquary)"},
			},
		},
		// --- Bulk alchemy ---
		{
			Name:                  "Nessa Brightbolt",
			Location:              "Bulk alchemy, The Hum — barrels stamped with Unionist warnings she ignores",
			Personality:           "Wholesale potion slinger: volume over mystique; jokes that the Viridian Shroud is 'just branding.'",
			WillingnessToPurchase: 0.92,
			ExchangeRate:          1.05,
			CategoriesObtained:    []string{"Potion"},
			Rules: []CatalogRuleSeed{
				{Category: "Potion", AllowedRarities: []string{"Common", "Uncommon", "Rare"}},
				{ItemName: "Healing Potion"},
				{ItemName: "Greater Healing Potion"},
				{ItemName: "Superior Healing Potion"},
				{ItemName: "Smog-Filter Lozenge"},
				{ItemName: "Aetheric Revivifier"},
			},
		},
		// --- Charts & navigation ---
		{
			Name:                  "Riven Slate",
			Location:              "Chart House — overlooking the keel-slips (maps smell of ink and river tar)",
			Personality:           "Navigator-merchant: traces routes in the air; despises 'as the crow flies' optimism.",
			WillingnessToPurchase: 0.86,
			ExchangeRate:          1.12,
			CategoriesObtained:    []string{"Tool", "Gear"},
			Rules: []CatalogRuleSeed{
				{ItemName: "Navigator's Tools"},
				{ItemName: "Cartographer's Tools"},
				{ItemName: "Sounding Lead & Line"},
			},
		},
		// --- Armorer ---
		{
			Name:                  "Iona Steele",
			Location:              "Steele & Rivet Armory — Ash Quarter (sign: crossed calipers)",
			Personality:           "No-nonsense armorer: measures you twice; mutters about Blue Coat 'standard issue' rot.",
			WillingnessToPurchase: 0.84,
			ExchangeRate:          1.14,
			CategoriesObtained:    []string{"Armor", "Shield"},
			Rules: []CatalogRuleSeed{
				{Category: "Armor", AllowedRarities: []string{"Common", "Uncommon"}},
				{ItemName: "Studded Leather"},
				{ItemName: "Chain Shirt"},
				{ItemName: "Leather"},
				{ItemName: "Clockwork Buckler"},
				{ItemName: "Standard Shield"},
				{ItemName: "Smelter's Gloves"},
			},
		},
		// --- Blue Coat surplus ---
		{
			Name:                  "Yao Lentham",
			Location:              "Blue Coat surplus window — 'Lawful recovery' goods, paperwork optional",
			Personality:           "Weary pawn-broker trope: knows every excuse; still logs serial numbers 'for the sergeant.'",
			WillingnessToPurchase: 0.62,
			ExchangeRate:          1.09,
			CategoriesObtained:    []string{"Simple Melee", "Gear", "Tool"},
			Rules: []CatalogRuleSeed{
				{Category: "Simple Melee", AllowedRarities: []string{"Common"}},
				{Category: "Gear", AllowedRarities: []string{"Common"}},
				{WeaponName: "Club"},
				{WeaponName: "Mace"},
				{ItemName: "Manacles"},
				{ItemName: "Hunting Trap"},
			},
		},
		// --- ECC clinical serums ---
		{
			Name:                  "Elias Rook",
			Location:              "ECC clinical pop-up — sterile white cloth over brass (rumors of Volt's serum crates)",
			Personality:           "Clinical supplier archetype: euphemisms for everything; too interested in your 'baseline vitals.'",
			WillingnessToPurchase: 0.76,
			ExchangeRate:          1.24,
			CategoriesObtained:    []string{"Potion", "Gear"},
			Rules: []CatalogRuleSeed{
				{ItemName: "Stabilizer Serum"},
				{ItemName: "Aetheric Revivifier"},
				{ItemName: "ECC Serum Sample Jar (sealed)"},
			},
		},
		// --- Import boutique ---
		{
			Name:                  "Marlowe Finch",
			Location:              "Finch Imports — claims North Axiom provenance (labels are... creative)",
			Personality:           "Department-store snob meets traveling salesman: compliments your purse, not you.",
			WillingnessToPurchase: 0.58,
			ExchangeRate:          1.42,
			CategoriesObtained:    []string{"Martial Melee", "Potion"},
			Rules: []CatalogRuleSeed{
				{Category: "Martial Melee", AllowedRarities: []string{"Common", "Uncommon"}},
				{WeaponName: "Rapier"},
				{WeaponName: "Scimitar"},
				{ItemName: "Potion of Heroism"},
				{ItemName: "Potion of Resistance"},
			},
		},
		// --- Black market arms ---
		{
			Name:                  "Grimjack Rourke",
			Location:              "No-Go alley mouth — oilcloth curtain, listens for Triple P boots",
			Personality:           "Black-market arms dealer: sells teeth and torque; jokes that the cartels are just 'wholesale clients.'",
			WillingnessToPurchase: 0.48,
			ExchangeRate:          1.33,
			CategoriesObtained:    []string{"Martial Melee", "Martial Ranged"},
			Rules: []CatalogRuleSeed{
				{Category: "Martial Melee", AllowedRarities: []string{"Uncommon", "Rare"}},
				{Category: "Martial Ranged", AllowedRarities: []string{"Uncommon", "Rare"}},
				{WeaponName: "Saw Cleaver"},
				{WeaponName: "Whirligig Saw"},
				{WeaponName: "Tesla Rifle"},
				{WeaponName: "Lightning Gun"},
				{ItemName: "No-Go Alley Chalk Set"},
			},
		},
		// --- Junk monger ---
		{
			Name:                  "Old Scratch Pummel",
			Location:              "Junk terrace above the copper runoffs — everything rattles, nothing matches",
			Personality:           "Junkmonger trope: pays surprisingly well for 'trash,' sells mystery bundles; may be three homunculi in a coat.",
			WillingnessToPurchase: 1.08,
			ExchangeRate:          0.94,
			CategoriesObtained:    []string{"Gear", "Tool"},
			Rules: []CatalogRuleSeed{
				{Category: "Gear", AllowedRarities: []string{"Common"}},
				{ItemName: "Rope, Hempen (50 feet)"},
				{ItemName: "Bag of Gears and Springs"},
				{ItemName: "Ball Bearings (bag of 1,000)"},
				{ItemName: "Bucket"},
				{ItemName: "Caltrops (bag of 20)"},
			},
		},
		// --- Dock chandler ---
		{
			Name:                  "Hester Blackreef",
			Location:              "Blackreef Chandlery — dock ward, sells to crews who dodge ETC manifests",
			Personality:           "Dockside provisioner: knows tides and bribes; whistles Unionist hymns ironically.",
			WillingnessToPurchase: 0.9,
			ExchangeRate:          1.07,
			CategoriesObtained:    []string{"Gear"},
			Rules: []CatalogRuleSeed{
				{Category: "Gear", AllowedRarities: []string{"Common", "Uncommon"}},
				{ItemName: "Rowboat"},
				{ItemName: "Grappling Hook"},
				{ItemName: "Rope, Silk (50 feet)"},
				{ItemName: "Dockyard Tar & Oakum Kit"},
				{ItemName: "Barrel"},
				{ItemName: "Oil (flask)"},
			},
		},
		// --- Arcane supplies ---
		{
			Name:                  "Varian Lux",
			Location:              "Lux Arcana Annex — 'Consult the Archives' satellite booth, wax seals everywhere",
			Personality:           "Snooty mage-supply clerk: asks if you're 'spell-safe' before handing over a component pouch.",
			WillingnessToPurchase: 0.7,
			ExchangeRate:          1.32,
			CategoriesObtained:    []string{"Gear"},
			Rules: []CatalogRuleSeed{
				{Category: "Gear", AllowedRarities: []string{"Common", "Uncommon"}},
				{ItemName: "Component Pouch"},
				{ItemName: "Arcane Focus (Rod)"},
				{ItemName: "Arcane Focus (Wand)"},
				{ItemName: "Arcane Focus (Orb)"},
				{ItemName: "Scholar's Pack"},
				{ItemName: "Alchemist's Supplies"},
			},
		},
	}
}
