package faradhaven_items

func intPtr(v int) *int       { return &v }
func strPtr(v string) *string { return &v }
func boolPtr(v bool) *bool    { return &v }

// Armor returns armor seeds
func Armor() []ItemSeed {
	return []ItemSeed{
		// Light Armor
		{
			Name:                "Padded",
			Description:         "Padded armor consists of quilted layers of cloth and batting.",
			Category:            "Armor",
			Rarity:              "Common",
			Cost:                "5 gp",
			Weight:              "8 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Light"),
			BaseAC:              intPtr(11),
			StealthDisadvantage: boolPtr(true),
		},
		{
			Name:         "Leather",
			Description:  "The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil.",
			Category:     "Armor",
			Rarity:       "Common",
			Cost:         "10 gp",
			Weight:       "10 lb.",
			Effects:      "",
			IsConsumable: false,
			ArmorType:    strPtr("Light"),
			BaseAC:       intPtr(11),
		},
		{
			Name:         "Studded Leather",
			Description:  "Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes.",
			Category:     "Armor",
			Rarity:       "Common",
			Cost:         "45 gp",
			Weight:       "13 lb.",
			Effects:      "",
			IsConsumable: false,
			ArmorType:    strPtr("Light"),
			BaseAC:       intPtr(12),
		},
		// Medium Armor
		{
			Name:         "Hide",
			Description:  "This crude armor consists of thick furs and pelts.",
			Category:     "Armor",
			Rarity:       "Common",
			Cost:         "10 gp",
			Weight:       "12 lb.",
			Effects:      "",
			IsConsumable: false,
			ArmorType:    strPtr("Medium"),
			BaseAC:       intPtr(12),
		},
		{
			Name:         "Chain Shirt",
			Description:  "Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather.",
			Category:     "Armor",
			Rarity:       "Uncommon",
			Cost:         "50 gp",
			Weight:       "20 lb.",
			Effects:      "",
			IsConsumable: false,
			ArmorType:    strPtr("Medium"),
			BaseAC:       intPtr(13),
		},
		{
			Name:                "Scale Mail",
			Description:         "This armor consists of a coat and leggings of leather covered with overlapping pieces of metal.",
			Category:            "Armor",
			Rarity:              "Uncommon",
			Cost:                "50 gp",
			Weight:              "45 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Medium"),
			BaseAC:              intPtr(14),
			StealthDisadvantage: boolPtr(true),
		},
		{
			Name:         "Breastplate",
			Description:  "This armor consists of a fitted metal chest piece worn with supple leather.",
			Category:     "Armor",
			Rarity:       "Uncommon",
			Cost:         "400 gp",
			Weight:       "20 lb.",
			Effects:      "",
			IsConsumable: false,
			ArmorType:    strPtr("Medium"),
			BaseAC:       intPtr(14),
		},
		{
			Name:                "Half Plate",
			Description:         "Half plate consists of shaped metal plates that cover most of the wearer's body.",
			Category:            "Armor",
			Rarity:              "Rare",
			Cost:                "750 gp",
			Weight:              "40 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Medium"),
			BaseAC:              intPtr(15),
			StealthDisadvantage: boolPtr(true),
		},
		// Heavy Armor
		{
			Name:                "Ring Mail",
			Description:         "This armor is leather armor with heavy rings sewn into it.",
			Category:            "Armor",
			Rarity:              "Common",
			Cost:                "30 gp",
			Weight:              "40 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Heavy"),
			BaseAC:              intPtr(14),
			StealthDisadvantage: boolPtr(true),
		},
		{
			Name:                "Chain Mail",
			Description:         "Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath.",
			Category:            "Armor",
			Rarity:              "Uncommon",
			Cost:                "75 gp",
			Weight:              "55 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Heavy"),
			BaseAC:              intPtr(16),
			StrengthRequirement: intPtr(13),
			StealthDisadvantage: boolPtr(true),
		},
		{
			Name:                "Splint",
			Description:         "This armor is made of narrow vertical strips of metal riveted to a backing of leather.",
			Category:            "Armor",
			Rarity:              "Uncommon",
			Cost:                "200 gp",
			Weight:              "60 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Heavy"),
			BaseAC:              intPtr(17),
			StrengthRequirement: intPtr(15),
			StealthDisadvantage: boolPtr(true),
		},
		{
			Name:                "Plate",
			Description:         "Plate consists of shaped, interlocking metal plates to cover the entire body.",
			Category:            "Armor",
			Rarity:              "Rare",
			Cost:                "1500 gp",
			Weight:              "65 lb.",
			Effects:             "Stealth: Disadvantage",
			IsConsumable:        false,
			ArmorType:           strPtr("Heavy"),
			BaseAC:              intPtr(18),
			StrengthRequirement: intPtr(15),
			StealthDisadvantage: boolPtr(true),
		},
	}
}
