package faradhaven_items

// StandardAdventuringGear returns individual PHB-style supplies, ammunition, containers, and common tools.
func StandardAdventuringGear() []ItemSeed {
	return []ItemSeed{
		// Ammunition
		{Name: "Arrows (20)", Description: "Twenty arrows for a bow.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "1 lb.", Effects: "Ammunition for bows.", IsConsumable: false},
		{Name: "Crossbow Bolts (20)", Description: "Twenty bolts for a crossbow.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "1.5 lb.", Effects: "Ammunition for crossbows.", IsConsumable: false},
		{Name: "Sling Bullets (20)", Description: "Twenty lead bullets for a sling.", Category: "Gear", Rarity: "Common", Cost: "4 cp", Weight: "1.5 lb.", Effects: "Ammunition for slings.", IsConsumable: false},
		{Name: "Blowgun Needles (50)", Description: "A bundle of thin needles for a blowgun.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "1 lb.", Effects: "Ammunition for blowguns.", IsConsumable: false},
		// Containers & carried goods
		{Name: "Backpack", Description: "A sturdy pack with straps and buckles.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "5 lb.", Effects: "Holds up to 1 cubic foot / 30 lb. of gear.", IsConsumable: false},
		{Name: "Barrel", Description: "A wooden barrel.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "70 lb.", Effects: "Holds about 40 gallons liquid or 4 cubic feet.", IsConsumable: false},
		{Name: "Basket", Description: "A woven basket.", Category: "Gear", Rarity: "Common", Cost: "4 sp", Weight: "1 lb.", Effects: "Holds 2 cubic feet / 40 lb.", IsConsumable: false},
		{Name: "Bedroll", Description: "A rolled blanket and pad for sleeping outdoors.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "7 lb.", Effects: "Comfortable rest in the wilderness.", IsConsumable: false},
		{Name: "Bell", Description: "A small metal bell.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "0 lb.", Effects: "Audible within 60 feet when rung.", IsConsumable: false},
		{Name: "Blanket", Description: "A warm wool blanket.", Category: "Gear", Rarity: "Common", Cost: "5 sp", Weight: "3 lb.", Effects: "Protection from cold while resting.", IsConsumable: false},
		{Name: "Book", Description: "A blank book or a printed volume.", Category: "Gear", Rarity: "Common", Cost: "25 gp", Weight: "5 lb.", Effects: "100 pages.", IsConsumable: false},
		{Name: "Bottle, Glass", Description: "A glass bottle that holds liquid.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "2 lb.", Effects: "Holds 1½ pints.", IsConsumable: false},
		{Name: "Bucket", Description: "A wooden bucket.", Category: "Gear", Rarity: "Common", Cost: "5 cp", Weight: "2 lb.", Effects: "Holds 3 gallons.", IsConsumable: false},
		{Name: "Chest", Description: "A wooden chest with a lock hasp.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "25 lb.", Effects: "Holds 12 cubic feet / 300 lb.", IsConsumable: false},
		{Name: "Flask or Tankard", Description: "A metal flask or drinking tankard.", Category: "Gear", Rarity: "Common", Cost: "2 cp", Weight: "1 lb.", Effects: "Holds 1 pint.", IsConsumable: false},
		{Name: "Jug or Pitcher", Description: "A clay jug.", Category: "Gear", Rarity: "Common", Cost: "2 cp", Weight: "4 lb.", Effects: "Holds 1 gallon.", IsConsumable: false},
		{Name: "Iron Pot", Description: "A cast-iron cooking pot.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "10 lb.", Effects: "Cooking over a fire.", IsConsumable: false},
		{Name: "Pouch", Description: "A belt pouch.", Category: "Gear", Rarity: "Common", Cost: "5 sp", Weight: "1 lb.", Effects: "Holds ⅙ cubic foot / 6 lb.", IsConsumable: false},
		{Name: "Sack", Description: "A cloth sack.", Category: "Gear", Rarity: "Common", Cost: "1 cp", Weight: "0.5 lb.", Effects: "Holds 1 cubic foot / 30 lb.", IsConsumable: false},
		{Name: "Vial", Description: "A small glass vial.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "0 lb.", Effects: "Holds 4 ounces.", IsConsumable: false},
		{Name: "Waterskin", Description: "A leather skin for water or wine.", Category: "Gear", Rarity: "Common", Cost: "2 sp", Weight: "5 lb. (full)", Effects: "Holds 4 pints.", IsConsumable: false},
		// Rope, light, movement
		{Name: "Rope, Hempen (50 feet)", Description: "Strong hemp rope.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "10 lb.", Effects: "Has 2 hit points and can be burst with DC 17 Strength.", IsConsumable: false},
		{Name: "Rope, Silk (50 feet)", Description: "Fine silk rope.", Category: "Gear", Rarity: "Common", Cost: "10 gp", Weight: "5 lb.", Effects: "Has 2 hit points; lighter than hemp.", IsConsumable: false},
		{Name: "Chain (10 feet)", Description: "A heavy iron chain with links.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "10 lb.", Effects: "Has 10 hit points and can be burst with DC 26 Strength.", IsConsumable: false},
		{Name: "Grappling Hook", Description: "An iron hook tied to a rope.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "4 lb.", Effects: "Climbing and securing lines.", IsConsumable: false},
		{Name: "Ladder (10-foot)", Description: "A folding or fixed wooden ladder.", Category: "Gear", Rarity: "Common", Cost: "1 sp", Weight: "25 lb.", Effects: "Reach high places.", IsConsumable: false},
		{Name: "Torch", Description: "A wooden stick topped with pitch-soaked cloth.", Category: "Gear", Rarity: "Common", Cost: "1 cp", Weight: "1 lb.", Effects: "Bright light 20 ft., dim 20 ft., 1 hour.", IsConsumable: true},
		{Name: "Candle", Description: "A wax candle.", Category: "Gear", Rarity: "Common", Cost: "1 cp", Weight: "0 lb.", Effects: "Dim light 5 ft., 1 hour.", IsConsumable: true},
		{Name: "Lantern, Hooded", Description: "A lantern with shutters to hide the light.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "2 lb.", Effects: "Bright 30 ft., dim 30 ft.; shutters as an action.", IsConsumable: false},
		{Name: "Lantern, Bullseye", Description: "A lantern with a reflective cone.", Category: "Gear", Rarity: "Common", Cost: "10 gp", Weight: "2 lb.", Effects: "Bright 60-ft cone, dim 60 ft.", IsConsumable: false},
		{Name: "Oil (flask)", Description: "A flask of lamp oil.", Category: "Gear", Rarity: "Common", Cost: "1 sp", Weight: "1 lb.", Effects: "Fuels a lantern 6 hours; can be lit as a splash weapon (5 ft., 5 fire).", IsConsumable: true},
		{Name: "Tinderbox", Description: "Flint, steel, and tinder.", Category: "Gear", Rarity: "Common", Cost: "5 sp", Weight: "1 lb.", Effects: "Light a torch or fire in 1 action.", IsConsumable: false},
		// Provisions
		{Name: "Rations (1 day)", Description: "Dried meat, fruit, and hardtack.", Category: "Gear", Rarity: "Common", Cost: "5 sp", Weight: "2 lb.", Effects: "Feeds one person one day.", IsConsumable: true},
		{Name: "Rations, Iron (1 day)", Description: "Unappetizing but dense travel food.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "2 lb.", Effects: "Feeds one person three days.", IsConsumable: true},
		// Field tools
		{Name: "Crowbar", Description: "A flat iron bar for prying.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "5 lb.", Effects: "Advantage on Strength checks to pry open objects.", IsConsumable: false},
		{Name: "Hammer", Description: "A carpenter's hammer.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "3 lb.", Effects: "Driving pitons or simple repairs.", IsConsumable: false},
		{Name: "Piton", Description: "A metal spike for climbing or securing rope.", Category: "Gear", Rarity: "Common", Cost: "5 cp", Weight: "0.25 lb.", Effects: "Climbing and anchoring.", IsConsumable: false},
		{Name: "Spikes, Iron (10)", Description: "Ten iron spikes.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "5 lb.", Effects: "Wedge doors, spike tracks.", IsConsumable: false},
		{Name: "Whetstone", Description: "A stone for sharpening blades.", Category: "Gear", Rarity: "Common", Cost: "1 cp", Weight: "1 lb.", Effects: "Maintain edged weapons.", IsConsumable: false},
		{Name: "Caltrops (bag of 20)", Description: "Sharp metal spikes that scatter on the ground.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "2 lb.", Effects: "20-ft square; DC 15 Dex save or stop and take 1 piercing.", IsConsumable: false},
		{Name: "Ball Bearings (bag of 1,000)", Description: "A bag of smooth metal balls.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "2 lb.", Effects: "10-ft square; DC 10 Dex save or fall prone.", IsConsumable: false},
		{Name: "Hunting Trap", Description: "A spring-loaded jaw trap.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "25 lb.", Effects: "DC 13 Dex save or take 1d4 piercing and be restrained.", IsConsumable: false},
		{Name: "Manacles", Description: "Metal cuffs joined by a chain.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "6 lb.", Effects: "Restrain a Small or Medium creature; DC 20 Dex or Str to escape.", IsConsumable: false},
		// Kits
		{Name: "Healer's Kit", Description: "Bandages, salves, and splints.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "3 lb.", Effects: "Stabilize a dying creature (10 uses).", IsConsumable: true},
		{Name: "Climber's Kit", Description: "Pitons, boot tips, gloves, and a harness.", Category: "Gear", Rarity: "Common", Cost: "25 gp", Weight: "12 lb.", Effects: "Advantage on climbing checks.", IsConsumable: false},
		{Name: "Herbalism Kit", Description: "Pouches of dried herbs and tools for remedies.", Category: "Tool", Rarity: "Common", Cost: "5 gp", Weight: "3 lb.", Effects: "Identify plants and craft antitoxins or salves.", IsConsumable: false},
		{Name: "Navigator's Tools", Description: "Sextant, charts, compass, and calipers.", Category: "Tool", Rarity: "Common", Cost: "25 gp", Weight: "2 lb.", Effects: "Sea and overland navigation.", IsConsumable: false},
		{Name: "Smith's Tools", Description: "Hammer, tongs, and files for metalwork.", Category: "Tool", Rarity: "Common", Cost: "20 gp", Weight: "8 lb.", Effects: "Forge and repair metal.", IsConsumable: false},
		{Name: "Woodcarver's Tools", Description: "Knives, gouges, and a small saw.", Category: "Tool", Rarity: "Common", Cost: "1 gp", Weight: "5 lb.", Effects: "Carve wood and craft small wooden objects.", IsConsumable: false},
		{Name: "Carpenter's Tools", Description: "Saws, planes, and nails.", Category: "Tool", Rarity: "Common", Cost: "8 gp", Weight: "6 lb.", Effects: "Build and repair wooden structures.", IsConsumable: false},
		{Name: "Mason's Tools", Description: "Trowel, hammer, and chisel for stone.", Category: "Tool", Rarity: "Common", Cost: "10 gp", Weight: "8 lb.", Effects: "Chisel stone and spot weaknesses in masonry.", IsConsumable: false},
		{Name: "Painter's Supplies", Description: "Brushes, pigments, and oils.", Category: "Tool", Rarity: "Common", Cost: "10 gp", Weight: "5 lb.", Effects: "Paint surfaces and create art.", IsConsumable: false},
		{Name: "Potter's Tools", Description: "A wheel and shaping tools for clay.", Category: "Tool", Rarity: "Common", Cost: "10 gp", Weight: "3 lb.", Effects: "Craft pottery and ceramics.", IsConsumable: false},
		{Name: "Weaver's Tools", Description: "Loom parts, thread, and needles.", Category: "Tool", Rarity: "Common", Cost: "1 gp", Weight: "5 lb.", Effects: "Weave cloth and repair fabric.", IsConsumable: false},
		{Name: "Leatherworker's Tools", Description: "Knives, needles, and scrapers for hide.", Category: "Tool", Rarity: "Common", Cost: "5 gp", Weight: "5 lb.", Effects: "Craft leather armor and goods.", IsConsumable: false},
		{Name: "Jeweler's Tools", Description: "Fine pliers, files, and a loupe.", Category: "Tool", Rarity: "Common", Cost: "25 gp", Weight: "2 lb.", Effects: "Appraise and craft jewelry.", IsConsumable: false},
		{Name: "Glassblower's Tools", Description: "A blowpipe and tools for molten glass.", Category: "Tool", Rarity: "Common", Cost: "30 gp", Weight: "5 lb.", Effects: "Craft glass vials and lenses.", IsConsumable: false},
		{Name: "Cartographer's Tools", Description: "Parchment, ink, rulers, and calipers.", Category: "Tool", Rarity: "Common", Cost: "15 gp", Weight: "6 lb.", Effects: "Create and read maps.", IsConsumable: false},
		{Name: "Calligrapher's Supplies", Description: "Inks, quills, and fine paper.", Category: "Tool", Rarity: "Common", Cost: "10 gp", Weight: "5 lb.", Effects: "Create documents and forgery checks.", IsConsumable: false},
		{Name: "Cobbler's Tools", Description: "Awls, hammers, and lasts for shoes.", Category: "Tool", Rarity: "Common", Cost: "5 gp", Weight: "5 lb.", Effects: "Craft and repair footwear.", IsConsumable: false},
		{Name: "Cook's Utensils", Description: "Pots, pans, and ladles.", Category: "Tool", Rarity: "Common", Cost: "1 gp", Weight: "8 lb.", Effects: "Cook meals and forage cooking.", IsConsumable: false},
		{Name: "Disguise Kit", Description: "Cosmetics, wigs, and props.", Category: "Tool", Rarity: "Common", Cost: "25 gp", Weight: "3 lb.", Effects: "Create a physical disguise.", IsConsumable: false},
		{Name: "Forgery Kit", Description: "Special inks, seals, and papers.", Category: "Tool", Rarity: "Common", Cost: "15 gp", Weight: "5 lb.", Effects: "Duplicate handwriting and documents.", IsConsumable: false},
		{Name: "Gaming Set", Description: "Dice, cards, or board pieces for games of chance.", Category: "Tool", Rarity: "Common", Cost: "1 sp", Weight: "0 lb.", Effects: "Play games; varies by set.", IsConsumable: false},
		{Name: "Poisoner's Kit", Description: "Vials, chemicals, and preservatives.", Category: "Tool", Rarity: "Common", Cost: "50 gp", Weight: "2 lb.", Effects: "Craft and apply poisons.", IsConsumable: false},
		{Name: "Cart", Description: "A two-wheeled cart pulled by one draft animal.", Category: "Gear", Rarity: "Common", Cost: "15 gp", Weight: "200 lb.", Effects: "Carries up to 2,000 lb. at half speed.", IsConsumable: false},
		{Name: "Carriage", Description: "A four-wheeled closed carriage.", Category: "Gear", Rarity: "Common", Cost: "100 gp", Weight: "600 lb.", Effects: "Passenger transport.", IsConsumable: false},
		{Name: "Rowboat", Description: "A small oared boat.", Category: "Gear", Rarity: "Common", Cost: "50 gp", Weight: "100 lb.", Effects: "Holds 3 Medium creatures; 1-1/2 mph.", IsConsumable: false},
		{Name: "Keelboat", Description: "A 60-ft river or lake boat with oars and a single sail.", Category: "Gear", Rarity: "Common", Cost: "3000 gp", Weight: "—", Effects: "Crew 15; carries tons of cargo.", IsConsumable: false},
		// Spellcasting foci & misc
		{Name: "Arcane Focus (Staff)", Description: "A specially constructed staff used as an arcane focus.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "4 lb.", Effects: "Spellcasting focus for arcane spells.", IsConsumable: false},
		{Name: "Arcane Focus (Rod)", Description: "A rod attuned as an arcane focus.", Category: "Gear", Rarity: "Common", Cost: "10 gp", Weight: "2 lb.", Effects: "Spellcasting focus for arcane spells.", IsConsumable: false},
		{Name: "Druidic Focus (Totem)", Description: "A wooden staff, yew wand, or totem.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "varies", Effects: "Spellcasting focus for druid spells.", IsConsumable: false},
		{Name: "Druidic Focus (Wooden Staff)", Description: "A staff carved with natural symbols.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "4 lb.", Effects: "Spellcasting focus for druid spells.", IsConsumable: false},
		{Name: "Holy Symbol (Amulet)", Description: "A symbol of a deity worn on a chain.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "1 lb.", Effects: "Spellcasting focus for cleric/paladin spells.", IsConsumable: false},
		{Name: "Holy Symbol (Reliquary)", Description: "A small box holding a sacred relic.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "2 lb.", Effects: "Spellcasting focus for cleric/paladin spells.", IsConsumable: false},
		{Name: "Component Pouch", Description: "A belt pouch of spell components.", Category: "Gear", Rarity: "Common", Cost: "25 gp", Weight: "2 lb.", Effects: "Material components for spells with no gp cost.", IsConsumable: false},
		{Name: "Quiver", Description: "A leather quiver for arrows.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "1 lb.", Effects: "Holds up to 20 arrows.", IsConsumable: false},
		// Writing & utility
		{Name: "Ink (1 ounce bottle)", Description: "Black or colored ink.", Category: "Gear", Rarity: "Common", Cost: "10 gp", Weight: "0 lb.", Effects: "Fills many pages.", IsConsumable: true},
		{Name: "Ink Pen", Description: "A quill or metal nib pen.", Category: "Gear", Rarity: "Common", Cost: "2 cp", Weight: "0 lb.", Effects: "Writing.", IsConsumable: false},
		{Name: "Parchment (one sheet)", Description: "A sheet of fine parchment.", Category: "Gear", Rarity: "Common", Cost: "1 sp", Weight: "0 lb.", Effects: "One page of writing.", IsConsumable: true},
		{Name: "Paper (one sheet)", Description: "A sheet of cheaper paper.", Category: "Gear", Rarity: "Common", Cost: "2 sp", Weight: "0 lb.", Effects: "One page of writing.", IsConsumable: true},
		{Name: "Map or Scroll Case", Description: "A cylindrical case for maps or scrolls.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "1 lb.", Effects: "Protects up to 10 scrolls.", IsConsumable: false},
		{Name: "Magnifying Glass", Description: "A lens for fine inspection.", Category: "Gear", Rarity: "Common", Cost: "100 gp", Weight: "0 lb.", Effects: "Advantage on checks to appraise or inspect small detail; can start fires in bright sun.", IsConsumable: false},
		{Name: "Mirror, Steel", Description: "A polished steel hand mirror.", Category: "Gear", Rarity: "Common", Cost: "5 gp", Weight: "0.5 lb.", Effects: "Peek around corners; signal.", IsConsumable: false},
		{Name: "Spyglass", Description: "A small telescope.", Category: "Gear", Rarity: "Common", Cost: "1000 gp", Weight: "1 lb.", Effects: "See detail at twice the distance.", IsConsumable: false},
		{Name: "Hourglass", Description: "A sand timer.", Category: "Gear", Rarity: "Common", Cost: "25 gp", Weight: "1 lb.", Effects: "Measures time in minutes.", IsConsumable: false},
		{Name: "Block and Tackle", Description: "Pulleys and rope to multiply lifting force.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "5 lb.", Effects: "Lift four times as much weight.", IsConsumable: false},
		{Name: "Merchant's Scale", Description: "A balance for weighing coins.", Category: "Gear", Rarity: "Common", Cost: "1 gp", Weight: "3 lb.", Effects: "Weigh objects up to 2 lb.", IsConsumable: false},
		{Name: "Signal Whistle", Description: "A loud metal whistle.", Category: "Gear", Rarity: "Common", Cost: "5 cp", Weight: "0 lb.", Effects: "Audible up to 600 feet.", IsConsumable: false},
		{Name: "Sealing Wax", Description: "Wax for sealing letters.", Category: "Gear", Rarity: "Common", Cost: "5 sp", Weight: "0 lb.", Effects: "Tamper-evident seals.", IsConsumable: true},
		{Name: "Soap", Description: "A bar of soap.", Category: "Gear", Rarity: "Common", Cost: "2 cp", Weight: "0 lb.", Effects: "Hygiene.", IsConsumable: true},
		{Name: "String (10 feet)", Description: "Twine or thin cord.", Category: "Gear", Rarity: "Common", Cost: "1 cp", Weight: "0 lb.", Effects: "Tie small objects.", IsConsumable: true},
		{Name: "Tent, two-person", Description: "A simple canvas tent.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "20 lb.", Effects: "Shelter for two.", IsConsumable: false},
		{Name: "Mess Kit", Description: "Tin plate, cup, and utensils.", Category: "Gear", Rarity: "Common", Cost: "2 sp", Weight: "1 lb.", Effects: "Cook and eat in the field.", IsConsumable: false},
		{Name: "Holy Water (flask)", Description: "Water blessed for use against fiends and undead.", Category: "Gear", Rarity: "Common", Cost: "25 gp", Weight: "1 lb.", Effects: "As an action, splash undead/fiend for 2d6 radiant.", IsConsumable: true},
		{Name: "Antitoxin (vial)", Description: "A vial of liquid that neutralizes poison.", Category: "Gear", Rarity: "Common", Cost: "50 gp", Weight: "0 lb.", Effects: "Advantage on saves against poison for 1 hour.", IsConsumable: true},
		{Name: "Acid (vial)", Description: "A vial of corrosive acid.", Category: "Gear", Rarity: "Common", Cost: "25 gp", Weight: "1 lb.", Effects: "Thrown 5 ft.: 2d6 acid to one target.", IsConsumable: true},
		{Name: "Alchemist's Fire (flask)", Description: "Sticky adhesive that burns fiercely.", Category: "Gear", Rarity: "Common", Cost: "50 gp", Weight: "1 lb.", Effects: "Hit: 1d4 fire at start of each turn; DC 10 Dex to extinguish.", IsConsumable: true},
		{Name: "Basic Poison (vial)", Description: "A vial of injury poison.", Category: "Gear", Rarity: "Common", Cost: "100 gp", Weight: "0 lb.", Effects: "Coat one weapon or 3 ammo: DC 10 Con save or 1d4 poison.", IsConsumable: true},
		{Name: "Abacus", Description: "A frame of beads for counting.", Category: "Gear", Rarity: "Common", Cost: "2 gp", Weight: "2 lb.", Effects: "Track numbers and tally costs.", IsConsumable: false},
	}
}
